# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

on:
#  push:
#    branches:
#      - main
  schedule:
    # POSIX cron syntax (every 2 hours), https://crontab.guru/#0_*/2_*_*_*
    - cron: "0 */3 * * *"

name: "Run"

env:
  PHP_EXTENSIONS: curl, fileinfo, intl, json, mbstring, simplexml, sodium, zlib

jobs:

  run-bot:
    name: "Run the bot and post to Mastodon"

    runs-on: ubuntu-latest

    env:
      MASTODON_TOKEN: ${{ secrets.MASTODON_TOKEN }}
      MASTODON_INSTANCE: ${{ secrets.MASTODON_INSTANCE }}

    steps:
      - name: "Checkout sources"
        uses: actions/checkout@v4

      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: ast, ${{ env.PHP_EXTENSIONS }}
          coverage: none

      - name: "Install dependencies with composer"
        uses: ramsey/composer-install@v3

      - name: "Run bot"
        run: php ./cli/run.php

      - name: "Commit log"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ":octocat: posted toot"
          file_pattern: "data/last_updated.json"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
